#!/usr/bin/env python

EnsureSConsVersion(3, 0, 0)
EnsurePythonVersion(3, 9)

import os

env = Environment(ENV = os.environ)

def makegodot():
  customgdargs: dict = {"precision": "double", "module_mono_enabled": "yes"}
  for key in ARGUMENTS:
    if key.startswith("gds_"):
      customgdargs[key[4:]] = ARGUMENTS[key]

  customgdargsstr: str = ""

  for key in customgdargs:
    customgdargsstr += key + "=" + str(customgdargs[key]) + " "

  env.Command(target = 'godot_engine', 
    source = 'godot/SConstruct', 
    action = [f'cd Server/godot && scons {customgdargsstr}'])

makegodot()
# ARGUMENTS.set()
# env.SConscript('godot/SConstruct')